[platformio]
default_envs = seeed_xiao_esp32s3
data_dir = data

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  crankyoldgit/IRremoteESP8266@^2.8.6
  bblanchon/ArduinoJson@^7.1.0

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3

[env:esp32dev]
board = esp32dev
