[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
  crankyoldgit/IRremoteESP8266@^2.8.6
  bblanchon/ArduinoJson@^7.1.0
